library TxSocketClientDll;
///<author>dev@bassetti.fr</author>
///<summary>Project file. This file is generated by TXUtils. If you include new files, do not forget to update the corresponding TXUCG project file./</summary>
///<summary>The project may require other files like RC files.</summary>



uses
  FastShareMem,
  System.SysUtils,
  System.Classes,
  TxSocketClientThread in 'Pas\TxSocketClientThread.pas';
  
exports
  //TxSocketClientThread
  ClientRequestThread,
  ClientSendFile,
  WriteStreamInt,
  WriteStreamStr,
  MemoryStreamToString;

begin
end.
